dist: jammy
language: python
python: 3.9
sudo: required
services:
- docker
install:
- pip install pipenv
- pipenv sync
env:
  global:
  - PY_COLOR=1
  - ANSIBLE_FORCE_COLOR=1
  jobs:
  # Java 8
  - DOCKER_IMAGE_BASE=debian:bullseye-slim JDK_VENDOR=adoptopenjdk JDK_MAJOR=8 JDK_VERSION=8u292-b10-3
    DOCKER_TAG_TO_PUBLISH=8u292-bullseye-adoptopenjdk-headless
  - DOCKER_IMAGE_BASE=debian:buster-slim JDK_VENDOR=adoptopenjdk JDK_MAJOR=8 JDK_VERSION=8u292-b10-3
    DOCKER_TAG_TO_PUBLISH=8u292-buster-adoptopenjdk-headless

  - DOCKER_IMAGE_BASE=ubuntu:bionic JDK_MAJOR=8 JDK_VERSION=8u342-b07-0ubuntu1~18.04
    DOCKER_TAG_TO_PUBLISH=8u342-bionic-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:focal JDK_MAJOR=8 JDK_VERSION=8u342-b07-0ubuntu1~20.04
    DOCKER_TAG_TO_PUBLISH=8u342-focal-openjdk-headless

  - DOCKER_IMAGE_BASE=quay.io/centos/centos:stream8 JDK_VENDOR=adoptopenjdk JDK_MAJOR=8
    JDK_VERSION=8u292_b10 DOCKER_TAG_TO_PUBLISH=8u292-centos8-adoptopenjdk-headless

  - DOCKER_IMAGE_BASE=debian:bullseye-slim JDK_VENDOR=corretto JDK_MAJOR=1.8.0 JDK_VERSION=1:8.302.08-1
    DOCKER_TAG_TO_PUBLISH=8u302-bullseye-corretto-headless
  - DOCKER_IMAGE_BASE=debian:buster-slim JDK_VENDOR=corretto JDK_MAJOR=1.8.0 JDK_VERSION=1:8.302.08-1
    DOCKER_TAG_TO_PUBLISH=8u302-buster-corretto-headless
  - DOCKER_IMAGE_BASE=quay.io/centos/centos:stream8 JDK_VENDOR=corretto JDK_MAJOR=1.8.0
    JDK_VERSION=1.8.0_302.b08 DOCKER_TAG_TO_PUBLISH=8u302-centos8-corretto-headless

  # Java 11
  - DOCKER_IMAGE_BASE=debian:buster-slim DOCKER_TAG_TO_PUBLISH=11-buster-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:buster-slim JDK_MAJOR=11 JDK_VERSION=11.0.16+8-1~deb10u1
    DOCKER_TAG_TO_PUBLISH=11.0.16-buster-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:bullseye-slim DOCKER_TAG_TO_PUBLISH=11-bullseye-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:bullseye-slim JDK_MAJOR=11 JDK_VERSION=11.0.16+8-1~deb11u1
    DOCKER_TAG_TO_PUBLISH=11.0.16-bullseye-openjdk-headless

  - DOCKER_IMAGE_BASE=ubuntu:bionic DOCKER_TAG_TO_PUBLISH=11-bionic-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:bionic JDK_MAJOR=11 JDK_VERSION=11.0.16+8-0ubuntu1~18.04
    DOCKER_TAG_TO_PUBLISH=11.0.16-bionic-openjdk-headless

  - DOCKER_IMAGE_BASE=ubuntu:focal DOCKER_TAG_TO_PUBLISH=11-focal-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:focal JDK_MAJOR=11 JDK_VERSION=11.0.16+8-0ubuntu1~20.04
    DOCKER_TAG_TO_PUBLISH=11.0.16-focal-openjdk-headless

  - DOCKER_IMAGE_BASE=ubuntu:jammy DOCKER_TAG_TO_PUBLISH=11-jammy-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:jammy JDK_MAJOR=11 JDK_VERSION=11.0.16+8-0ubuntu1~22.04
    DOCKER_TAG_TO_PUBLISH=11.0.16-jammy-openjdk-headless

  - DOCKER_IMAGE_BASE=centos:7 JDK_MAJOR=11 JDK_VERSION=11.0.12.0.7 DOCKER_TAG_TO_PUBLISH=11.0.12.0.7-centos7-openjdk-headless
  - DOCKER_IMAGE_BASE=quay.io/centos/centos:stream8 JDK_MAJOR=11 JDK_VERSION=11.0.13.0.8
    DOCKER_TAG_TO_PUBLISH=11.0.13.0.8-centos8-openjdk-headless

  # Java 17
  - DOCKER_IMAGE_BASE=debian:bullseye-slim DOCKER_TAG_TO_PUBLISH=17-bullseye-openjdk-headless
  - DOCKER_IMAGE_BASE=debian:bullseye-slim JDK_MAJOR=17 JDK_VERSION=17.0.4+8-1~deb11u1
    DOCKER_TAG_TO_PUBLISH=17.0.4-bullseye-openjdk-headless

  - DOCKER_IMAGE_BASE=ubuntu:focal DOCKER_TAG_TO_PUBLISH=17-focal-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:focal JDK_MAJOR=17 JDK_VERSION=17.0.4+8-1~20.04
    DOCKER_TAG_TO_PUBLISH=17.0.4-focal-openjdk-headless

  - DOCKER_IMAGE_BASE=ubuntu:jammy DOCKER_TAG_TO_PUBLISH=17-jammy-openjdk-headless
  - DOCKER_IMAGE_BASE=ubuntu:jammy JDK_MAJOR=17 JDK_VERSION=17.0.4+8-1~22.04
    DOCKER_TAG_TO_PUBLISH=17.0.4-jammy-openjdk-headless
script:
- pipenv run molecule test --scenario-name=${JDK_VENDOR:-default}
notifications:
  webhooks:
  - https://galaxy.ansible.com/api/v1/notifications/
deploy:
  provider: script
  script: ANSIBLE_ROLES_PATH=../ pipenv run ansible-playbook dockerhub/main.yml --extra-vars
    "docker_hub_email=${DOCKER_EMAIL} docker_hub_username=${DOCKER_USERNAME} docker_hub_password='${DOCKER_PASSWORD}'
    docker_image_base=${DOCKER_IMAGE_BASE} jdk_version=${JDK_VERSION} jdk_major=${JDK_MAJOR}
    jdk_vendor=${JDK_VENDOR}  docker_tag=${DOCKER_TAG_TO_PUBLISH}"
  on:
    branch: master
    condition: "$JDK_VERSION"
