---

- name: Java | Install OpenJDK implementation
  include_tasks: install_openjdk.yml
  tags:
    - install

- name: Java | Import certificates into Java Keystore
  include_tasks: import_certs.yml
  when: java_certs is defined
  tags:
    - certs
